on:
    push:
      branches:
        - dev
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_KEY }}
      - name: Trust gitlab.com host
        run: ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
      - name: Push mirror
        run: |
          git remote add gitlab git@gitlab.com:vneshka/vneshka-pro-landing.git
          git push gitlab --all --force
